server:
  port: 8085

spring:

  application:
    name: NOTIFICATION-SERVICE

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3307}/${MYSQL_DATABASE:revhive_db}?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC}
    username: ${SPRING_DATASOURCE_USERNAME:${MYSQL_USER:root}}
    password: ${SPRING_DATASOURCE_PASSWORD:${MYSQL_PASSWORD:2022}}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

  jackson:
    serialization:
      fail-on-empty-beans: false

eureka:

  client:
    register-with-eureka: true
    fetch-registry: true

    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}

  instance:
    prefer-ip-address: true

logging:
  level:
    org.springframework.web.socket: DEBUG
    org.hibernate.SQL: DEBUG