apiVersion: apps/v1
kind: Deployment

metadata:
  name: notification-service
  namespace: revhive
  labels:
    app: notification-service

spec:
  replicas: 1

  selector:
    matchLabels:
      app: notification-service

  template:
    metadata:
      labels:
        app: notification-service

    spec:
      containers:
        - name: notification-service
          image: krroot14/notification-service:latest
          imagePullPolicy: Always

          ports:
            - containerPort: 8088

          env:
            - name: SPRING_PROFILES_ACTIVE
              value: docker

            - name: SPRING_DATASOURCE_URL
              value: jdbc:mysql://mysql:3306/revhive_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true

            - name: SPRING_DATASOURCE_USERNAME
              value: root

            - name: SPRING_DATASOURCE_PASSWORD
              value: 23@Tanushree

            - name: EUREKA_URI
              value: http://service-registry:8761/eureka

          resources:
            limits:
              cpu: "500m"
              memory: "512Mi"
            requests:
              cpu: "250m"
              memory: "256Mi"
